name: 'Cake Action'
description: 'Run a Cake script as part of your build.'
author: 'Enrico Campidoglio'
branding:
  icon: 'package'
  color: 'yellow'
inputs:
  script-path:
    description: 'The path of the Cake script to run.'
    required: false
    default: 'build.cake'
  target:
    description: 'The name of the task to execute. Note that this argument must be supported by the script.'
    required: false
  cake-version:
    description: 'The version of Cake to install.'
    required: false
  cake-bootstrap:
    description: 'Flag for if Cake modules should be installed/bootstrapped.'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'lib/main.js'
